# Generated by Django 5.2.6 on 2025-12-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('inner_d', models.IntegerField(verbose_name='Внутренний диаметр')),
                ('outer_d', models.IntegerField(verbose_name='Внешний диаметр')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('ammount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Подшипник',
                'verbose_name_plural': 'Подшипники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='текст отзыва')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bearings.client')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер заказа')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bearings.client')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(verbose_name='Количество')),
                ('bearing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bearings.bearing')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bearings.order')),
            ],
            options={
                'verbose_name': 'Состав заказа',
                'verbose_name_plural': 'Составы заказов',
            },
        ),
    ]
