# Generated by Django 5.2.6 on 2025-12-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(null=True, upload_to='clients', verbose_name='Изображение'),
        ),
    ]
