# Generated by Django 5.2.6 on 2025-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearings', '0002_client_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearing',
            name='picture',
            field=models.ImageField(null=True, upload_to='bearings', verbose_name='Изображение'),
        ),
    ]
