# Generated by Django 5.2.6 on 2025-12-09 19:10

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearings', '0004_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='totp_key',
            field=models.CharField(blank=True, default=pyotp.random_hex, max_length=128, null=True),
        ),
    ]
